### PR TITLE
If Developer mode is enabled on device, default to 'Remote debugging'…

### LINKED ISSUE #874: Automatically enable `Remote Debugging` and `Redirect Console to Logcat` when in Developer Mode (Oculus' Developer Mode, adb, or Android Studio)
## Hardware
Oculus Go
ab56151

## Steps to Reproduce

1. Ensure Developer Mode is enabled for your device (from the Oculus mobile companion app, open `Settings`, select the headset in the list, then enable from `More Options > Developer Mode`)
2. Run in the Terminal: `adb uninstall org.mozilla.vrbrowser`
3. Sideload an APK from `master` via `adb` or from Android Studio
4. The first two developer options, `Remote Debugging` and `Redirect Console to Logcat`, in `Settings > Developer Options` are default to `Off`.

## Current Behavior
The first two developer options, `Remote Debugging` and `Redirect Console to Logcat`, in `Settings > Developer Options` are default to `Off`.

## Expected Behavior
If we know FxR is in Developer Mode, it'd be nice for the first two developer options, `Remote Debugging` and `Redirect Console to Logcat`, in `Settings > Developer Options` to default to `On`.

### PR DESCRIPTION
**Pull request by philip-lamb**
… and 'Console logs' both enabled. Fixes #874.

### CODE REVIEW

**Comment by MortimerGoro** [comment]
It works for me in the Vive Focus, but not in Oculus Go.

**Comment by bluemarvin** [comment]
Remote debugging is disabled by default for both performance and security reasons. The tradeoffs should probably be understood before proceeding with this patch.

**Comment by philip-lamb** [comment]
> Remote debugging is disabled by default for both performance and security reasons. The tradeoffs should probably be understood before proceeding with this patch.

I got an authoritative response from the Developer Tools team, which notes that the performance effect is limited to the loading of the debugger server and dependencies (a load time of 300ms was mentioned) and that if this was undesirable, loading of the debugger could be delayed until after the UI was up. Otherwise, there is no performance effect unless a session is connected.

> It works for me in Vive Focus, but not in Oculus Go.

I got a response from the Oculus engineers and have added the switch used in their implementation.

**Comment by MortimerGoro** [comment]
Is there any security implication of enabling it by default?

**Comment by philip-lamb** [comment]
> Is there any security implication of enabling it by default?

No, but considering that having these options enabled by default imposes a small time penalty on app launch and that many developers who have their device in developer mode won't also need these on by default,  I think the method proposed in https://github.com/MozillaReality/FirefoxReality/issues/1027 is better.

**Pull request closed without merging**
