### PR TITLE
Focus/Full screen should remember window size set by user

### LINKED ISSUE #105: Focus/Full screen should remember window size set by user
STR:
1) Go into focus mode
2) Set window size to 3x
3) Leave exit focus mode
4) Go back into focus mode

Expected result: Screen should still be 3x
Actual result: screen is default size.

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #105

### CODE REVIEW

**Comment by MortimerGoro** [comment]
We need to handle custom sizes too, check this method

```
    // WidgetManagerDelegate.Listener
    @Override
    public void onWidgetUpdate(Widget aWidget) {
        if (aWidget != mBrowserWidget) {
            return;
        }

        // Browser window may have been resized, adjust the navigation bar
        float targetWidth = aWidget.getPlacement().worldWidth;
        float defaultWidth = WidgetPlacement.floatDimension(getContext(), R.dimen.browser_world_width);
        targetWidth = Math.max(defaultWidth, targetWidth);
        // targetWidth = Math.min((targetWidth, defaultWidth * 2.0f);

        float ratio = targetWidth / defaultWidth;
        mWidgetPlacement.worldWidth = targetWidth;
        mWidgetPlacement.width = (int) (WidgetPlacement.dpDimension(getContext(), R.dimen.navigation_bar_width) * ratio);
        mWidgetManager.updateWidget(this);
    }
```

**Comment by keianhzo** [comment]
Reverted Fullscreen to always 2x and added support for custom focus mode presets.

**Comment by bluemarvin** [comment]
I'm still seeing issues with resizing windows.

STR:
1) Go into manual resize mode.
2) Stretch window so it is taller.
3) Exit focus mode.
expected result: Window returns to default size.
actual result: Window stays tall while content resizes and gets stretched.

Also, when in resize mode after a manual resize, clicking the 1x button doesn't change the height of the window and it stay tall.

**Comment by keianhzo** [comment]
Doesn't look like it's related to this fix. It's also happening on master and it seems to be related to the way we are handling the browser widget resizing in handleResizeEvent. It only happens in the case you described.

I'll file a bug and we can address this in a follow up task.

**Comment by bluemarvin** [comment]
Sorry, got my issues mixed up. Was thinking of #108

**Pull request merged**
