### PR TITLE
Dialogs refactoring

### LINKED ISSUE #2131: FxR cross app dialog standarization
**Is your feature request related to a problem? Please describe.**
Dialogs in the app are using different styles that cause consistency issues. We should standardize the dialog styles based on the latest spec: https://trello.com/c/25qaflLv/400-sl-7-componentsdialogs

- [x] Permissions
- [x] Restart
- [x] PopUp Blocking
- [x] Crash dialog
- [x] Remove Max Windows dialog
- [x] Collect Voice samples
- [x] What's new
- [x] Sign out
- [x] Voice Search

**Describe the solution you'd like**
Create base dialog styles and reuse them in the different dialogs.

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #2296: The "Pop-Ups Permissions" entries do not have a hover or click state
**[Affected Versions]:**
- Firefox Reality version 7 RC1 (b772e6d7)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The Firefox Reality browser is opened.
- Make sure the "Block Pop-Up Windows" option is enabled.
- Make sure the "Pop-Ups Permissions" list has at least 2 entries.

**[Steps to reproduce]:**
1. Go to Settings -> Privacy & Security.
2. Click the “Advanced” button for the “Block Pop-Up Windows” option.
3. Using the controller hover the pointer over one of the sites from the list.
4. Observe the behaviour.
5. Using the controller click and hold one of the sites from the list.
6. Observe the behaviour

**[Expected results]:**
Step 4. The "Pop-Ups Permissions" entries container are highlighted with an iron color.
Step 6. The "Pop-Ups Permissions" entries container are highlighted with a void color.

**[Actual results]:**
Step 4. The "Pop-Ups Permissions" entries do not have a hover effect.
Step 6. The "Pop-Ups Permissions" entries do not have a click effect and the dismiss button disappears.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=1OF66kuxt9AZGVfnUqYttvCuT8CxKW86S).

### LINKED ISSUE #2307: need a better way to show/hide popups and other UI
We get a lot of bugs that boil down to "this piece of UI doesn't disappear when it should", primarily with popups.  See bugs like #2301 as an example.

There should be a way to easily and reliably hide UI based on user actions, without having to control each other piece of UI individually.

### LINKED ISSUE #2421: The up and down arrows for the Preferred Website Language are overlapping
**[Notes]:**
- If the arrows are clicked the language is only be moved up

**[Affected Versions]:**
-  Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Open the "Language" card from Settings.
2. Click the "Edit" button for the "Display Website Language" option.
3. Hover over the languages displayed on the right side.
4. Click the "+" button for 2 languages to add them to the list on the left.
5. Hover over the languages on the middle from the list on the left.
6. Observe the right side of the language.

**[Expected results]:**
- The Up and Down arrows are correctly displayed.

**[Actual results]:**
- The Up and Down arrows are overlapping.

**[Additional Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1w8DIz84VisZAiKS1LcRfy4s5INik-r8Q).

### LINKED ISSUE #2498: The app crashes if the First Explainer page is dismissed by clicking outside it's borders if it was opened from "Send Tab to Device" option
**[Notes]:**
- If the First Explainer page is triggered from "View Tabs", when clicking outside it's borders, the View Tabs and First Explainer page are overlapping and only after the "Start Browsing" button is clicked the app crashes. If the "Sign In" button is clicked the sign in process is started and the app is NOT crashed.
Here is a screen recording with this behavior: [link](https://drive.google.com/open?id=17mEGMZGs1AGC8IpikKUhEugSQsQkGvU7).

**[Affected Versions]:**
- Firefox Reality version 8-33512130 (8dd6bffd)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- You are not logged into an FxA account.

**[Steps to reproduce]:**
1. Click the "Hamburger" button.
2. Click the "Send Tab to Device" option.
3. Click outside the First Explainer page boundaries.
4. Observe the behavior.

**[Expected results]:**
- The page is dismissed.

**[Actual results]:**
- The app crashes.

**[Additional Notes]:**
- This issue is also reproducible with the production version of the app (v7).
- This issue is not reproducible is dismissed if the First Explainer page is displayed after installing/updating the app.
- Attached are crash the report, logcat and the screen recording of the issue:[link]().
	- Screen recording: [link](https://drive.google.com/open?id=1CgxUswDWeXHXVfBuGEahlGdGHgEHQvN3).
	- Logcat: [link](https://drive.google.com/open?id=1G-lWF8Ncf8qWrJOMLQgfvD0n5N98vC03).
	- Crash Report: [link](https://crash-stats.mozilla.com/report/index/bp-83c55d84-0fcf-48c2-a64d-1f92a0191218).

### PR DESCRIPTION
**Pull request by keianhzo**
Closes #2131 Fixes #2307 Fixes #2296 Fixes #2421 Fixes #2498 Refactored app dialogs to reuse as much code as possible. This should help avoid issues with different style, behaviors and positions of app dialogs. We still can improve in reusing styles but this PR is big enough already.

- Added a SettingsDialogWidget reused by:
    + Send Tab dialog
    + Clear History dialog
- A PromptDialogWidget reused by:
    + Restart dialog
    + Crash dialog
    + PopUp block dialog
    + What's new dialog
    + Sign Out dialog
- Browser alert and confirm generic dialogs with their own style
- App alerts now have a common style (also reusing PromptDialogWidget):
    + No Internet
    + Not entitled
    + Poor performance
    + Voice Samples collection
- Removed Max Windows dialog
- Make Settings links to be opened in new foreground  tabs (Help, Report, Feedback)
- Voice Search Dialog style updated
- Added empty popup exceptions panel text
- Removed unused resources

### CODE REVIEW

**Comment by bluemarvin** [comment]
The crash dialog is missing the check mark allowing the user to always send the crash report with out prompting.

**Comment by bluemarvin** [comment]
What is the clear cache dialog?

**Comment by keianhzo** [comment]
@bluemarvin I've restored the checkbox in the crash dialog. Also I've fixed a broken received in debug mode (it probably never worked)

**Comment by bluemarvin** [comment]
I just noticed the crash dialog has the wrong icon, it is using the FxR logo and it should have the crying fox logo.

**Comment by keianhzo** [comment]
I dropped it to make the dialogs more standard, I've restored it.

**Pull request merged**
