### PR TITLE
Fixes #2562 Handle shift switching also for text keys

### LINKED ISSUE #2562: [Keyboard] The keyboard is not switched back to lowercases when clicking the "Å" key
**[Affected Versions]:**
- Firefox Reality version 8-33611921 (67403bf2)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.
- The keyboard's language is set to Danish.

**[Steps to reproduce]:**                                        
1. Focus the Awesomebar.
2. Click once on the uppercase arrow from the keyboard.
3. Click the "Å" key and observe the keyboard.

**[Expected results]:**
- The keyboard switches back to lowercase.

**[Actual results]:**
- The keyboard remains on uppercase.

**[Notes]:**
- This issue is reproducible on all languages where the "å" character is available (Polish, Norwegian, Swedish).
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=13n5KlV4pg2dEFOSxiH_5bXzGAuNA_X7L).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2562 Handle shift switching also for text keys

### CODE REVIEW

**Comment by keianhzo** [comment]
@MortimerGoro can you reproduce this? I can't reproduce it after the fix

**Comment by bluemarvin** [comment]
I can't reproduce the issue in latest master: e84c0fb95c9eb6ac90f2ce49af7381fc18c6268c

**Comment by bluemarvin** [comment]
@MortimerGoro what are your STR? I was able to reproduce it 100% at first but now I can't.

**Comment by MortimerGoro** [comment]
@bluemarvin STR:
- Open Swedish keyboard
- Click left or right shit to make the keyboard uppercase
- Click the Å letter
- The keyboard is still uppercase

**Comment by bluemarvin** [comment]
@MortimerGoro Using your STR, this patch seems to work for me. I am able to reproduce the issue on master also.

**Comment by bluemarvin** [comment]
Actually, the problem I'm seeing is with the english keyboard, long pressing on the `A` key with shift pressed, clicking `Å` does not return the keyboard to lower case. I see this with this patch applied.

**Comment by keianhzo** [comment]
@bluemarvin yep, that's a bug. I've pushed a fix. I've also made the overlays to be dismissed in the back button is pressed if they are opened, feels more natural that closing the whole keyboard.

**Pull request merged**
