### PR TITLE
Reduce false positive performance monitor detection

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

**Comment by bluemarvin** [comment]
Depends on https://github.com/MozillaReality/vrb/pull/66

**Comment by bluemarvin** [comment]
Now depends on https://github.com/MozillaReality/vrb/pull/67

**Comment by MortimerGoro** [comment]
I tried ShaderToy and it took a long time to detect the jank. It's that on purpose to avoid false positives?

**Comment by bluemarvin** [comment]
How did you test it? If you launch with the broken url it will take some time to detect. But I don’t consider that the typical use case. But I could have broken it. The way it should work is after the frame rate has stabilized junk should take about two seconds to detect.

**Comment by MortimerGoro** [comment]
> How did you test it? If you launch with the broken url it will take some time to detect. But I don’t consider that the typical use case. But I could have broken it. The way it should work is after the frame rate has stabilized junk should take about two seconds to detect.

I launched with the default URL, typed shadertoy in the awesome bar and open it from the Google search

**Comment by bluemarvin** [comment]
Okay, sounds broken 😓. I’ll take a look when back to my computer.

**Comment by keianhzo** [comment]
I've made some tests on the Go and false positives detection has improved for regular pages but shadertoy takes too long time to be detected and sometimes it crashes the app.

**Comment by keianhzo** [comment]
@bluemarvin See to work much better than before, less false positives and although it still takes a while to jump in for performance intensive sites like shadertoy, it doesn't feel as long as before.

**Comment by MortimerGoro** [comment]
I get some crashes when trying Shadertoy:

```
2019-07-24 10:28:09.825 976-1334/? W/ActivityManager: Force removing ActivityRecord{b8a0723 u0 org.mozilla.vrbrowser.dev/org.mozilla.vrbrowser.VRBrowserActivity t13930}: app died, no saved state
2019-07-24 10:35:50.867 976-1087/? I/ActivityManager: Process org.mozilla.vrbrowser.dev (pid 3474) has died
```

Probably related to memory limit because I don't see a stacktrace.

**Comment by bluemarvin** [comment]
I landed this because the false positives on the Focus were getting really annoying. We can tune further with follow ups or just turn it off if we don't feel it is helping.

**Pull request merged**
