### PR TITLE
Add support for clearing window color before GV does the first composition

### LINKED ISSUE #1641: Browser window and nav bar should appear together when making a new window.
## Configuration

Firefox Reality version: all
Firefox Reality build ID: all

Hardware: all

## Steps to Reproduce

1. Create a new window.

## Current Behavior

The nav bar is shown but the window is not show until gecko renders to the surface texture.
## Expected Behavior

A window should be shown even if it is blank.
## Possible Solution

Draw a temporary quad placeholder for the window. It could be white for regular windows and purple for private browsing. Not drawing the window immediately on window creation makes FxR seem unresponsive and slow. We would need to have different implementations for layers and non-layer window rendering.

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #1641

### CODE REVIEW

**Comment by MortimerGoro** [comment]
We are considering postponing this to v1.5 until the new GV compositor callback API ready. It's hard to get the perfect delay without that callback.

**Comment by philip-lamb** [comment]
OK, LMK what you decide. If not landed by 2019-08-29 17:00PDT I'll bump to 1.5.

**Comment by bluemarvin** [comment]
I've created two GeckoView issues to help enable this feature:
https://bugzilla.mozilla.org/show_bug.cgi?id=1578947
https://bugzilla.mozilla.org/show_bug.cgi?id=1578949

**Comment by bluemarvin** [comment]
I rebased this so that I could look into working on the GV fixes needed.

**Comment by bluemarvin** [comment]
After rebasing this no longer works on WaveVR devices.

**Comment by bluemarvin** [comment]
HTC is working, now just waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1578947 to land in GV nightly.

**Comment by bluemarvin** [comment]
Looks like the custom frag shader does not work on NoAPI/Daydream and draws a white border around the window. Investigating...

**Comment by bluemarvin** [comment]
> Looks like the custom frag shader does not work on NoAPI/Daydream and draws a white border around the window. Investigating...

After more testing, this appears to be an Android 9 bug as this patch works on the Mirage Daydream device which is Android 8.

**Pull request merged**
