### PR TITLE
Private windows recreation fixes

### LINKED ISSUE #1544: Private browsing window fails to be recreated on resume
## Hardware

Oculus
## Steps to Reproduce

1. Launch FxR
2. Switch to private browsing
3. Pause FxR by pressing oculus home button.
4. Resume FxR

## Current Behavior

The private browsing screen fails to be displayed
Screen_Shot_1908083702

## Possible Solution

The private browsing screen should be displayed.

### LINKED ISSUE #1545: Crash in telemetry
## Hardware

Quest
## Steps to Reproduce
1) Launch FxR
2) Enter private browsing
3) exit private browsing by pressing the private browsing icon in the tray
4) Notice the close button is still visible over the window
5) click the close button

## Current Behavior

https://crash-stats.mozilla.com/report/index/4ab38a12-a12a-49ff-b905-f6d920190808

## Expected Behavior

Close button should not be visible and telemetry shouldn't crash

### LINKED ISSUE #1561: Wrong URL show for default private browsing window.
## Steps to Reproduce

1. Launch FxR
2. Switch to Private Browsing
3. Switch back to non-Private Browsing
4. Switch back to Private Browsing

## Current Behavior

The URL is incorrect. It shows the unlocked padlock and has a `data:` URL:
image

## Expected Behavior

The URL should not show the unlocked padlock and should say `Search the Web or enter address`

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #1544, Fixes #1545 and Fixes #1561 Also fixes the curved mode being activated after adding a second window if disabled and private sessions not being hidden after restoring and showing on top of the regular windows. Also cherry picked a SessionStack refactor from other of my PRs to get rid of an intermediate structure that can be avoided that also fixes some bugs when handling sessions inside the session stack.

### CODE REVIEW

**Comment by keianhzo** [comment]
@bluemarvin Totally missed that, I've reverted it although I have to say that without being aware it totally felt like a bug to me.

**Comment by bluemarvin** [comment]
I only knew about because I reviewed it. 😅 It isn’t what would expect either.

**Comment by bluemarvin** [comment]
This still isn't working for me. STR (easiest to repro with NoAPI):
1) launch FxR
2) switch to Private Browsing
3) Press Overview button
4) Swipe to kill FxR
5) Relaunch FxR

Results:
Private browsing window is not present.

Expected:
Private browsing window should be visible.

**Comment by keianhzo** [comment]
@bluemarvin Makes sense that happens in noapi killing the app. The recent apps button triggers the onPause state but not onStop. I've moved the save state call to onPause, that should solve the issue.

**Comment by bluemarvin** [comment]
@keianhzo I can still recreate the issue where switching to private mode and then swipe closing FxR in NoAPI. To be clear I see this on headsets too, it's just easier to reproduce with NoAPI.

**Comment by bluemarvin** [comment]
From an offline discussion it was noted that the private browsing session are being saved and restored and it was agreed this is probably not the desired behavior. It was agreed to wait to land this PR until that issue was addressed.

**Comment by keianhzo** [comment]
@bluemarvin should work as expected now.

**Pull request merged**
