### PR TITLE
Fixes #3276 Update search codes

### LINKED ISSUE #3276: Sending the wrong google search code
## Configuration

Firefox Reality version: v10
Firefox Reality build ID: 2020-04-24

Hardware: Oculus Quest

## Steps to Reproduce

1. Perform a voice search
2. Look at the URL bar
3.

## Current Behavior
The search code sent is `firefox-b-1-m`

## Expected Behavior

Should have `firefox-b-1-o`

See also https://github.com/MozillaReality/FirefoxReality/issues/885

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #3276 Update search codes and cleanup old dead code not needed anymore.

Override default AC Google search plugins to include the correct search codes.

@mkaply Can please verify if everything looks good? Also we still have some overrides for search plugins that I'm not sure if still apply: https://github.com/MozillaReality/FirefoxReality/issues/248#issuecomment-412278211

### CODE REVIEW

**Comment by bluemarvin** [comment]
The issue(#3276)  says it should be `firefox-b-1-o` but I'm seeing `firefox-b-1-m-o`
org mozilla vrbrowser-20200429-094316

**Comment by mkaply** [comment]
What exactly changed to cause this?

**Comment by mkaply** [comment]
What exactly changed to cause this?

And I'm really confused, this patch seems to be still using b-1-m-o? 

Per the original report, it;s:

firefox-b-1-o | firefox-b-o

**Comment by keianhzo** [comment]
@mkaply So we only need to update **google-b-m** and **google-b-1-m** to use **firefox-b-o** and **firefox-b-1-o** respectively? **google** and **google-2018** stay the same? I've updated the PR.

**Comment by bluemarvin** [comment]
I'm still not sure what it *should* be but the current PR matches what is reported in the initial issue now.

**Comment by bluemarvin** [comment]
I'm going to land this for rc4 and if it needs further adjustment we can address in a follow up.

**Pull request merged**
