### PR TITLE
Fixes #2545 Handle media playback state when the media is unloaded

### LINKED ISSUE #2545: The play/pause button remains displayed under inactive windows when a page on the same website is open
**[Affected Versions]:**
- Firefox Reality version 8-33580833 (777a0ae00)

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is open.

**[Steps to reproduce]:**                                        
1. Go to a video page and play the video.
2. Click on a link that leads to a page on the same website.
3. Open a new window from the tray.
4. Observe the initial window.

**[Expected results]:**
-  The play/pause button is not displayed under the window if it does not contain active videos.

**[Actual results]:**
- The play/pause button remains displayed for pages on the same website.

**[Notes]:**
- Navigating to another website or refreshing the page causes the button to disappear.
- While the button is actionable, it doesn’t affect anything.
- This issue is also reproducible after using the “Back” and “Forward” buttons.
- Attached is a recording of the [issue](https://drive.google.com/file/d/1hdzaQgpIuUKFUD4oxCttRUpq8j6_5RxS/view?usp=sharing).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2545 Handle media playback state when the media is unloaded

### CODE REVIEW

**Comment by bluemarvin** [comment]
I'm having a hard time reproducing the issue. When I click on a video on either youtube or vimeo, they just start playing regardless of my autoplay state.

**Comment by keianhzo** [comment]
@bluemarvin I can reproduce it 100% following the steps from the video in the issue.

**Comment by bluemarvin** [comment]
> @bluemarvin I can reproduce it 100% following the steps from the video in the issue.

Ah, I see the STR is different from the video. I'll try again.

**Comment by bluemarvin** [comment]
I tired reproducing and now I never see the media button.

**Comment by keianhzo** [comment]
@MortimerGoro @bluemarvin this has already been added to https://github.com/MozillaReality/FirefoxReality/pull/2705. Closing

**Pull request closed without merging**
