### PR TITLE
update icons and logos with low-poly versions (fixes issue #1016)

### PR DESCRIPTION
**Pull request by cvan**
for issue #1016

<hr>

# Before

### Release

image

image

### Developer Edition

image

image

# After

### Pico G2
image

image

### Oculus Go
image

image

### Pico G2
image

image

### Oculus Go
image

image

<hr>

[Figma source files](https://www.figma.com/file/E4jCjG4R3xjlRUqft7zb3DEa/Logos?node-id=4%3A9) _(Public, Read-only)_

### CODE REVIEW

**Comment by cvan** [comment]
> ### Developer Edition
> 
> #### Oculus Go
> image

Let me know if I should change the graphic to be grayscale when FxR is loading in the Developer Edition build. Thanks!

**Comment by philip-lamb** [comment]
Other places I still see the old logo or variants:
```
app/src/main/res/drawable/sad_fox.png
app/src/main/res/drawable/ffgvr_background.png
app/src/main/res/drawable/ffgvr_foreground.png
app/src/main/res/mipmap-hdpi/ic_launcher.png
app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
app/src/main/res/mipmap-hdpi/ic_launcher_round.png
app/src/main/res/mipmap-mdpi/ic_launcher.png
app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
app/src/main/res/mipmap-mdpi/ic_launcher_round.png
app/src/main/res/mipmap-xhdpi/ic_launcher.png
app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
app/src/main/res/mipmap-xxhdpi/ic_launcher.png
app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
app/src/main/ic_launcher-web.png
app/src/wavevr/res/mipmap-mdpi/ic_launcher.png
app/src/wavevr/res/mipmap-hdpi/ic_launcher.png
app/src/wavevr/res/mipmap-xxxhdpi/ic_launcher.png
app/src/wavevr/res/mipmap-xxhdpi/ic_launcher.png
app/src/wavevr/res/mipmap-xhdpi/ic_launcher.png

**Comment by cvan** [comment]
@philip-lamb good catches, will update. thanks!

**Comment by cvan** [comment]
@philip-lamb: thanks again!

I'm updating the icons [**here**](https://www.figma.com/file/E4jCjG4R3xjlRUqft7zb3DEa/Branding?node-id=11%3A47), and will update this PR shortly.

will keep this checklist below to keep track of them:

- [x] <s>app/src/main/res/drawable/sad_fox.png</s> (no changes needed, IMO)
- [ ] app/src/main/res/drawable/ffgvr_background.png
- [ ] app/src/main/res/drawable/ffgvr_foreground.png
- [ ] app/src/main/res/mipmap-hdpi/ic_launcher.png
- [ ] app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
- [ ] app/src/main/res/mipmap-hdpi/ic_launcher_round.png
- [ ] app/src/main/res/mipmap-mdpi/ic_launcher.png
- [ ] app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
- [ ] app/src/main/res/mipmap-mdpi/ic_launcher_round.png
- [ ] app/src/main/res/mipmap-xhdpi/ic_launcher.png
- [ ] app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
- [ ] app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
- [ ] app/src/main/res/mipmap-xxhdpi/ic_launcher.png
- [ ] app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
- [ ] app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
- [ ] app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
- [ ] app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
- [ ] app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
- [ ] app/src/main/ic_launcher-web.png
- [ ] app/src/wavevr/res/mipmap-mdpi/ic_launcher.png
- [ ] app/src/wavevr/res/mipmap-hdpi/ic_launcher.png
- [ ] app/src/wavevr/res/mipmap-xxxhdpi/ic_launcher.png
- [ ] app/src/wavevr/res/mipmap-xxhdpi/ic_launcher.png
- [ ] app/src/wavevr/res/mipmap-xhdpi/ic_launcher.png

**Comment by MortimerGoro** [comment]
@cvan FWIW I normally use https://github.com/laptrinhcomvn/app-icon-generator to generate all the Android icon sizes from a big logo image

**Comment by cvan** [comment]
@MortimerGoro: darn, I should've asked how they were generated. wasn't sure if they were manually or automatically generated. anyway, done now. I was able to do it well enough [here](https://www.figma.com/file/E4jCjG4R3xjlRUqft7zb3DEa/Branding?node-id=11%3A47), and I made some adjustments as needed so things looked normal.

feel free to review this as well, @philip-lamb too.

[here's the final updated list.](https://github.com/MozillaReality/FirefoxReality/pull/1033#issuecomment-474599886)

**Pull request merged**
