### PR TITLE
WIP: FxA, Sync and Send Tab integrations

### PR DESCRIPTION
**Pull request by grigoryk**
This PR integrates latest version of the FxA account manager from android-components, and adds just enough code to allow signing-in via settings, signing out, synchronizing history & bookmarks and receiving tabs sent from other Firefox devices.

Follow-up:
- #1420 Enable glean telemetry support (so that we know how sync is doing)
- #1419 Obtain a production FxA client ID (currently using a sample one)
- #1397 megazord configuration for places and fxa libs
- #1395 bookmarks UI needs folder support
- #1398 better account management UI, currently there are just sign-in/sign-out/reconnect buttons

### CODE REVIEW

**Comment by bluemarvin** [comment]
FYI, QR code probably isn’t feasible on most headsets due to limited or no camera support. A PIN number would probably be best.

**Comment by keianhzo** [comment]
@grigoryk It seems that when starting the app we are getting a null account as it seems like the accountmanager initAsync hasn't finished yet so you have to pause/resume the activity to actually start getting events as the the corroutine has already finished.

**Comment by keianhzo** [comment]
@jvonitter This will require some disgn and product decision making before merging, as @grigoryk said, at least bookmarks folders support and a sync button for an initial v1 with manual polling. Also finding the right place in the settings for the sign-in button.

**Comment by grigoryk** [comment]
Updated this PR:
- bookmarks are now displayed right after signing-in
- account password changes (and other 'need to reconnect') events are now handled; there's now a "Reconnect" button
- some further cleanup and bugfixes

Started on bookmarks navigation improvement work in #1396.

**Comment by grigoryk** [comment]
Filed a few follow-up issues that can be handled separately from this PR (see https://github.com/MozillaReality/FirefoxReality/pull/1389#issue-296890586 for a list).

**Comment by grigoryk** [comment]
grigoryk:combinedFxaDesktopBookmarks has the rebased versions of this PR on top of #1395.

**Comment by MortimerGoro** [comment]
great job @grigoryk! I tried `grigoryk:combinedFxaDesktopBookmarks` branch, I was able to log in on the first attempt and bookmark Sync worked perfectly.

Regarding `Send tab to device`, I have to restart FxR to detect it. Is there and event to receive it live?

**Comment by grigoryk** [comment]
Filed some more follow-up tickets. Closing this, work will land on a feature branch in #1417.

**Pull request closed without merging**
