### PR TITLE
Use local androidx.appcompat aar with android.speech dependencies removed

### PR DESCRIPTION
**Pull request by MortimerGoro**

### CODE REVIEW

**Comment by philip-lamb** [comment]
Tested OK on Go and Focus. I'm going to merge so we can get a new RC built for Oculus Store ingestion.

**Comment by cvan** [comment]
I thought we were going to determine by emailing Oculus the root cause of Oculus' validator requiring the string name be manually removed. The APK for this branch could be tested against Oculus' validator by uploading it to the alpha channel (or another channel).

**Comment by philip-lamb** [comment]
Yep. Build is in progress and I'll push it to Oculus alpha for testing as soon as it's built.

**Comment by cvan** [comment]
An APK generated from Android Studio could be uploaded to the Oculus Store for validation. It seems like this PR was merged without resolved action items and additional testing/reviewing. Can we make sure we have sign off before merging PRs, even if a release date is approaching imminently?

**Comment by philip-lamb** [comment]
There were no open code-related action items. I did a thorough local test before merging. I'm happy to discuss the process more interactively, just ping me.

**Pull request merged**
