### PR TITLE
Update icon background size and color

### LINKED ISSUE #311: Update FxR icon back ground to match other assets?
@thenadj currently the background for the various FxR icons is white. Should it be change to the same purple being used for the app store assets?

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #311 #320 Updated background color and updated icon size.

screenshot 8

43922949-20e50c92-9bd5-11e8-9c22-b3726da34eb7

### CODE REVIEW

**Comment by bluemarvin** [comment]
https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/drawable/ffgvr_background.png

and

https://github.com/MozillaReality/FirefoxReality/blob/master/app/src/main/res/drawable/ffgvr_foreground.png

need to be updated. The background should be purple and the Fx logo should probably be smaller.

Here is a photoshop template:
https://developers.google.com/vr/downloads/stencil-examples.zip

Taken from:
https://developers.google.com/vr/distribute/daydream/publishing-requirements

Additionally, here is a foreground and background taken from a GVR example:
vr_icon
vr_icon_background

**Comment by bluemarvin** [comment]
It looks like Wave doesn't use standard android icon correctly so we will need a custom one for the Focus. From looking at the example Wave applications, the icon back ground should not have any transparency and go edge to edge. It seems the home environment adds rounded corners to the full icon. So the Fx logo should probably also be a little bigger in this custom icon.

**Comment by thenadj** [comment]
@bluemarvin Can this be done programmatically or do you need a new file from me?

**Comment by bluemarvin** [comment]
@thenadj I think @keianhzo has everything he needs, unless you want something other than a solid color behind the logo.

**Comment by keianhzo** [comment]
Fixed GVR and Wave Icons. I couldn't test the wave fix in the actual headset so please let me know if it's fixed.

**Comment by bluemarvin** [comment]
gvr-icon

I think our Fx logo is too large on Daydream? All the other apps have much smaller top layer icons.

**Comment by bluemarvin** [comment]
I've verified Wave is fixed.

**Comment by thenadj** [comment]
Yes, it's too large. Please match size for consistency.

**Comment by keianhzo** [comment]
Previous version was inside the Daydream template bounds for the icon but it seems that they leave plenty of padding. Updated Daydream size to better match the other platform icons.

**Pull request merged**
