### PR TITLE
Update gradle and android tools

### PR DESCRIPTION
**Pull request by MortimerGoro**

### CODE REVIEW

**Comment by bluemarvin** [comment]
@MortimerGoro 
```
> Task :app:lintVitalNoapiArm64Release
Calling mockable JAR artifact transform to create file: /root/.gradle/caches/transforms-2/files-2.1/002ac786e5db5bd4dab659bfe9a9f3e3/android.jar with input /opt/platforms/android-28/android.jar
/opt/FirefoxReality/app/src/main/res/layout/setting_radio_group.xml:19: Error: @id/environmentRadio is not a sibling in the same RelativeLayout [NotSibling]
                android:layout_toStartOf="@id/environmentRadio"
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   Explanation for issues of type "NotSibling":
   Layout constraints in a given ConstraintLayout or RelativeLayout should
   reference other views within the same relative layout (but not itself!)
1 errors, 0 warnings
> Task :app:lintVitalNoapiArm64Release FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:lintVitalNoapiArm64Release'.
> Lint found fatal errors while assembling a release target.
  
  To proceed, either fix the issues identified by lint, or modify your build script as follows:
  ...
  android {
      lintOptions {
          checkReleaseBuilds false
          // Or, if you prefer, you can continue to check for errors in release builds,
          // but continue the build even when errors are found:
          abortOnError false
      }
  }
  ...
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 7m 45s
75 actionable tasks: 74 executed, 1 up-to-date
[taskcluster 2019-04-23 10:17:53.581Z] === Task Finished ===
[taskcluster 2019-04-23 10:17:53.582Z] Unsuccessful task run with exit code: 1 completed in 632.359 seconds
```

**Comment by MortimerGoro** [comment]
Fixed

**Comment by bluemarvin** [comment]
Trying to do a local build of oculusvrArmDebug-armeabi-v7a:

```
FAILURE: Build failed with an exception.

* What went wrong:
buildOutput.apkData must not be null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 30s
33 actionable tasks: 26 executed, 7 up-to-date
```

**Comment by MortimerGoro** [comment]
@bluemarvin I had the same problem when switching gradle/tools versions. You just need to do a Build->Clean

**Pull request merged**
