### PR TITLE
Do not resize fullscreen window size if the window size is actually larger than the threshold.

### LINKED ISSUE #1362: Full screen transitions in Hubs do not work as expected
## Hardware
Oculus Quest

## Steps to Reproduce
- Set your screen size in FxR to 3x
- Go to hubs.mozilla.com and create an enter a room
- When in VR, hit the "magic wand" button in the HUD to open the media browser
- Go through the flow to show the media browser full screen by clicking on Continue
- Notice the content is clipped and the viewport is reset to 1x

## Current Behavior
- When an app calls the fullscreen API, it appears the CSS layout is happening at the user's viewport size (1x-3x) but the actual screen quad is reset to 1x. This results in clipping of the content.

## Expected Behavior
- FxR should *either*
  - Restore the user's screen size properly when entering full screen mode, and apply the proper CSS layout
  - Always set the screen size to 3x in full screen mode (I would suggest this option, since it provides the best analog to "full screen" in an immersive browser, and works nicely this way in Oculus Browser)

## Possible Solution
- When an application requests full screen support, change the size to 3x and fade the background, regardless of the user's non-full screen viewport settings.

## Context
We rely upon this behavior to provide nice, full UX for browsing, etc.

```
```

</details>

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #1362

### CODE REVIEW

**Comment by bluemarvin** [comment]
I'm confused what the issue is and what the expected behavior should be. I feel like there should be two screen sizes. One for normal browsing and one for full screen. But is seems to me that no mater what size I set for the full screen window, it reverts to the standard window size next time? I also could not reproduce the clipping described in the STR for the issue. Am I missing a step?

**Comment by MortimerGoro** [comment]
I also see a problem outside of the Hubs layout issue. STR:

- Set the web size to 3X
- Load https://davidwalsh.name/demo/fullscreen.php
- Enter Fullscreen. The window size reduces to 1.75x.

Isn't it weird that fullscreen reduces the actual window size? If a user wants a youtube fullscreen video in 3X he can't because of this resize.

cc @jvonitter This may require design decision.

**Comment by bluemarvin** [comment]
I agree that our window sizing is confusing. It rarely behaves the way I would expect and doesn't seem to retain the size I set it to.

**Comment by jvonitter** [comment]
thanks for the heads up @MortimerGoro . I'll check in with UX about it

**Comment by thenadj** [comment]
Looking at it and need some time to reply... expect answers early next week.

**Comment by jvonitter** [comment]
@thenadj and I just discussed this and we think you're right, sizing the screen down like that is weird. What we'd like to do is update the logic to be:
If you enter full screen with a view that is 1.75x or smaller, it enlarges to 1.75x. 
Anything bigger than that size doesn't change size.

Sound ok?

**Comment by MortimerGoro** [comment]
```
I just discussed this and we think you're right, sizing the screen down like that is weird. 
What we'd like to do is update the logic to be:
If you enter full screen with a view that is 1.75x or smaller, it enlarges to 1.75x.
Anything bigger than that size doesn't change size.
```
Thanks! that logic is what the PR is supposed to do.

**Pull request merged**
