### PR TITLE
Correctly layout quads on a parent cylinder. Center tray with active window.

### LINKED ISSUE #1521: multiwindow polish - center tray with active window
The tray should be centered beneath the active window (instead of staying fixed in the center)

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #1521

### CODE REVIEW

**Comment by MortimerGoro** [comment]
@jvonitter @thenadj APK for testing: https://send.firefox.com/download/1680ed60b990aad4/#sLaHOuepFsdzFdQd9peV_A

**Comment by keianhzo** [comment]
@MortimerGoro Tooltips don't seem to be aligned with the tray icons positions. Also the settings window should show up above the tray, at least that's what I understood and what I implemented in my initial PR. Also I tried with a curved settings windows and looked nice good, maybe we could also add that.

**Comment by MortimerGoro** [comment]
@keianhzo I updated the PR to also center settings. Tooltips are misaligned also on `master`, so I don't think it's related to this PR

**Comment by MortimerGoro** [comment]
@keianhzo I'm merging this so it starts getting tested by QA. Add a follow-up if you find something. You can rebase your branch for the curved tooltip on tray.

**Pull request merged**
