### PR TITLE
support video playback on Vimeo 360 video pages via WebCompat Web Extension (fixes issue #841)

### PR DESCRIPTION
**Pull request by cvan**
for issue #841

<hr>

this enables a user to play 360° videos from landing on a Vimeo video page organically, from a search or a link that's not directly linked to from the Content Feed (where the videos are linked like this: https://player.vimeo.com/video/<id>?canvas=1&mozVideoProjection=360_auto)

### CODE REVIEW

**Comment by philip-lamb** [comment]
Based on comments from @cvan, there is an issue with Vimeo searches coming from Google on mobile platform. Holding for now.

**Comment by MortimerGoro** [comment]
I tried https://vimeo.com/208799259, it added the 360_auto parameter and worked when I clicked enter full screen. 

Would it also be possible to go to fullscreen vr when on video play?

**Comment by philip-lamb** [comment]
It works when using the desktop UA, but mobile and VR UAs don't. Perhaps we need the same kind of UA override to force the desktop layout that we currently also need for the youtube webext.

**Comment by MortimerGoro** [comment]
I updated this PR to fix the black screen issue: #1299

Test URL: https://player.vimeo.com/video/295051863?mozVideoProjection=360&autoplay=1

**Comment by bluemarvin** [comment]
The `mozVideoProject=360` doesn't seem to work for me. Is it supposed to go into immersive video mode when going full screen?

**Comment by philip-lamb** [comment]
It needed the desktop UA fix, which somehow got overwritten. I've re-added that and it now works as intended. With fix from @MortimerGoro this looks good to land and is a big improvement to the Vimeo experience.

**Comment by philip-lamb** [comment]
fixes #841 fixes #1299

**Pull request merged**
