### PR TITLE
Refine Multiple window telemetry

### LINKED ISSUE #2030: move telemetry computation off client
We have too much telemetry computation at the client side. Ideally, we would upload raw data to the data server and do the computation there.

- [x] examine current telemetry and determine what need to be broken out
- [x] make those changes client-side
- [ ] update server-side logic so all the queries don't break
- [ ] update wiki and data review as needed

related to #1420

### PR DESCRIPTION
**Pull request by daoshengmu**
Fixes #2030.

### CODE REVIEW

**Comment by daoshengmu** [comment]
I have confirmed it works as I thought. @keianhzo  Let's do the review first, then I will update our Wiki and start the data review then.

**Comment by keianhzo** [comment]
@daoshengmu ready to start the data rwview

**Comment by daoshengmu** [comment]
# Request for data collection review form
 **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
 
 1. **What questions will you answer with this data?**
 
 *  Frequency of window moves per session.
 *  Frequency of window resizes per session.
 *  Time spent in active window position, per session.
 *  How long are one, two or three windows open, per session?
 *  How many windows are open at a time, per session?
 
 2. **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**
 
 * Establish baselines or measure changes in product or platform quality or performance.
 * Provide information essential for advancing a business objective such as supporting OKRs.
 * Determine whether a product or platform change has an effect on user or browser behavior.
  
 3. **What alternative methods did you consider to answer these questions? Why were they not sufficient?**
 
 * N/A
 
 4. **Can current instrumentation answer these questions?**
 
 * We did it at  #1443, but the current telemetry mechanism is not optimized at the client side and some data are wrong., so we need to refine them.
 
 5. **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data collection](https://wiki.mozilla.org/Firefox/Data_Collection) [categories](https://wiki.mozilla.org/Firefox/Data_Collection#Data_Collection_Categories) on the found on the Mozilla wiki.**
 
 * All data is Category 2.
 
 6. **How long will this data be collected?**
 
 * I want this data to be collected for 6 months initially (potentially renewable).
 
 7. **What populations will you measure?**

 * All release, beta, and nightly users with telemetry enabled.
 
 8. **Please provide a general description of how you will analyze this data.**
 
 * Review with UX design team to inform improvements to this feature and future feature development. Review with developers to identify bugs.
 
 9. **Where do you intend to share the results of your analysis?**
 
 * Only within the team.

**Comment by daoshengmu** [comment]
@harraton Please help do [data review](https://github.com/MozillaReality/FirefoxReality/pull/2323#issuecomment-558803716), and the [wiki](https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#multi-window) has been updated.

**Comment by jvonitter** [comment]
Since this data was already reviewed as part of #1329 , I think it's ok to merge as long as we didnt add any new metrics. I do still want official approval from @harraton when she's back (and we can make any necessary updates then)

**Comment by daoshengmu** [comment]
We didn't add new telemetry and just refine existing ones. So. we are going to merge it and please let me know if there is other concerns, we will address it then.

**Pull request merged**
