### PR TITLE
Add support for Oculus App Linking

### PR DESCRIPTION
**Pull request by MortimerGoro**
I tried to test this using this code from a different app id:
```
ovrApplicationOptionsHandle options = ovr_ApplicationOptions_Create();
ovrID id = 2180252408763702;
ovr_ApplicationOptions_SetDeeplinkMessage(options, "https://www.mozilla.org");
ovr_Application_LaunchOtherApp(id, options);
```
But it  shows the Oculus Store page with a update button.

### CODE REVIEW

**Comment by bluemarvin** [comment]
I think to test you might need to upload a build to the alpha channel?

**Comment by bluemarvin** [comment]
Also, I wanted to use JSON for the message body so we could easily add things in the future. Or even allow multiple URLs to be sent at once.

**Comment by MortimerGoro** [comment]
Ok, I'll add a json format and then we can test with alpha channel

**Comment by bluemarvin** [comment]
Great, just let me know when you are ready to test it.

**Comment by MortimerGoro** [comment]
@bluemarvin ready for testing

**Pull request merged**
