### PR TITLE
Ensure browser UI appears at correct level for 6DoF head tracking

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

**Comment by bluemarvin** [comment]
@cvan Give this a try and see if that fixes the UI offset for 6DoF. Probably should hold off landing until we have time to test thoroughly.

**Comment by bluemarvin** [comment]
> this is a fantastic improvement. the Tray is no longer obscured and the dialogues appear at eye level.
> 
> could we tweak the height a bit so the Media Controls are closer to average height level?
> 

I think the media controls are on the high side? My PR should put the eyes at the same level as the Go.

**Comment by bluemarvin** [comment]
I'm going to merge. The video UX should probably be a different issue?

**Comment by cvan** [comment]
> I'm going to merge. The video UX should probably be a different issue?

yeah, it is - I filed it separately privately.

**Pull request merged**
