### PR TITLE
Fixes #2919 Fixes #2673 Fixes #2641 Hide Youtube fixes

### LINKED ISSUE #2641: The controls from the right side of the Youtube videos are not displayed for all videos on windows having the 0.5x size
**[Affected Versions]:**
- Firefox Reality version 8-40131058 (dd3477c).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.
- The 0.5x size is set for the window.

**[Steps to reproduce]:**
1. Navigate to the Youtube website.
2. Play for example the following video: https://www.youtube.com/watch?v=8CdcCD5V-d8.
3. Observe the controls from the right side of the video.

**[Expected results]:**
- The "Settings", "Miniplayer", "Theater Mode", "Play on TV"and "Full Screen" buttons are displayed.

**[Actual results]:**
- The "Settings", "Miniplayer", "Theater Mode" , "Play on TV" and "Full Screen" buttons are NOT displayed.

**[Notes]:**
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1Z51qZD7ObDAhYKRrX-LwwNfgvuzxHVmI).

### LINKED ISSUE #2673: The next video is wrongly played or the recommended videos are displayed after a video was played in immersive mode
**[Affected Versions]:**
- Firefox Reality version 8 RC1 (7a444d0).

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Play a 360 video in immersive mode.
2. Wait until the video finises playing.
3. Observe the behavior.

**[Expected results]:**
- The video is exited from immersive mode if the next video is not compatible.
OR
- An option to replay the video is displayed.

**[Actual results]:**
- Autoplay ON: The next video is played even if it is not compatible.
- Autoplay OFF: The window with the suggested videos is displayed in immersive mode and it's not actionable.

**[Notes]:**
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1FwbfXer49PAsZNIfhK34fPqmBFnWRXRm).

### LINKED ISSUE #2919: Youtube video controls are not displayed correctly after resize to 1X or 0,5X in theater mode
**[Affected Versions]:**
- Firefox Reality version 9 rc7 (b68f946)

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to a normal video on YouTube and enter theater/full screen mode.
2. Resize the screen to 1x.
3. Observe the video controls.
4. Resize the screen to 0,5x.
5. Observe the video controls.

**[Expected results]:**
- The video controls are displayed correctly on the bottom of the screen.

**[Actual results]:**
- The video controls are displayed partially after resizing to 1x
- The video controls are not displayed after resizing to 0,5x.

**[Notes]:**
- This issue is not reproducible with sizes greater than 1x.
- If the video screen is scrolled down, the controls appear.
- Attached is a video of this [issue](https://drive.google.com/file/d/1Vfc_fhT_xunNUGpC7aqQkI7gjIoBelJR/view)

### LINKED ISSUE #2947: [Youtube] The video wrongly skips forward/backwards when double clicking the video's controls
**[Affected Versions]:**
- Firefox Reality version 10-40720037 (dbb8ed3a)
- Firefox Reality version 9 rc10 (324719f).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- Oculus Quest - Android 7.1.1
- Pico Neo2 - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Navigate to Youtube.com and play a normal video.
2. Double click on the "Play" button.
3. Observe the behavior.

**[Expected results]:**
- The video is paused/played.

**[Actual results]:**
- The video skips back 10 seconds.

**[Notes]:**
- If the buttons from the right side of the video are double clicked the video skips forward with 10 seconds.
- This issue is also reproducible in theater mode.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1rcQJekufHSohvEVGPURVNXlTOK-xLw47).

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #2919 Fixes #2947 Fixes #2673 Hide YouTube overlays in immersive

### CODE REVIEW

**Comment by bluemarvin** [comment]
This also doesn't seem to address #2673 as when I manually select a projection, it stays in that projection for the next video that is played.

**Comment by keianhzo** [comment]
@bluemarvin Don't seem to be able to reproduce the fullscreen issue with the provided STRs.

Regarding:

> This also doesn't seem to address #2673 as when I manually select a projection, it stays in that projection for the next video that is played.

AFAIK that's always been like that. We currently auto-select the projection based on a custom `mozVideoProjection` URL param that we append to the URL when the user plays the video, then we parse it when entering immersive video mode. If another video is played while in immersive, we don't update the video projection. We could add webext communication to notify of the new playback start and send the projection parameter to update the projection mode.

**Comment by bluemarvin** [comment]
> @bluemarvin I Don't seem to be able to reproduce the fullscreen issue with the provided STRs.
> 
> Regarding:
> 
> > This also doesn't seem to address #2673 as when I manually select a projection, it stays in that projection for the next video that is played.
> 
> AFAIK that's always been like that. We currently auto-select the projection based on a custom `mozVideoProjection` URL param that we append to the URL when the user plays the video, then we parse it when entering immersive video mode.
> If another video is played while in immersive, we don't update the video projection. We could add webext communication to notify on the new playback start and send the projection parameter to update the projection mode.

@keianhzo It has always been that way as far as I know. That's why I was not clear how this PR addresses #2673. If we don't plan to address it, we should close with a won't fix tag. I'll review again to see if I can reproduce the issue I was seeing.

**Comment by keianhzo** [comment]
@bluemarvin I've updated I was missing a case and you were probably hitting it.

**Pull request merged**
