### PR TITLE
Use user configuration to initialize session UA and viewport settings

### LINKED ISSUE #1985: The mobile version of a webpage is displayed even though the desktop user agent is selected in settings on newly created windows
**[Affected Versions]:**
- Firefox Reality version 5-32821846 RC1 (58b59be3)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2
- Lenovo Mirage Solo - Android 8.0.0

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Go to Settings->Display and for the "User-Agent Mode" setting select the "Desktop" option.
2. Dismiss the menu and click the “New Window” button from the menu tray.
3. In the newly created window visit a website that supports both mobile and desktop versions. (e.g. facebook, twitter, twitch, ...)
4. Observe the loaded webpage.

**[Expected results]:**
- The desktop version of the webpage is displayed.

**[Actual results]:**
- The mobile version of the webpage is displayed.

**[Additional Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1sHTWIgOEbU3n5zPKFfFefzCxiyME2gAR/view?usp=sharing).

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes  #1985

### CODE REVIEW

**Comment by bluemarvin** [comment]
This doesn't seem to work correctly for me. STR:
1) Set desktop UA in setting/display
Expected:
The desktop icon should be checked
Actual:
The desktop icon is not checked
org mozilla vrbrowser-20191025-085713

**Comment by bluemarvin** [comment]
I feel like the current implementation is sort of broken. I think changing the value in the display dialog should not change any of the currently open windows and should only be used for any new windows created. And once a window is created, the only way to toggle it is with the desktop icon.

**Comment by MortimerGoro** [comment]
Updated the PR to not change currently opened windows. It only affects the new ones.

**Comment by MortimerGoro** [comment]
fixes #2078

**Pull request merged**
