### PR TITLE
Add long press reload that bypasses cache

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

**Comment by bluemarvin** [comment]
@MortimerGoro @keianhzo I'm not convinced the developer switch is necessary. I would okay with removing it and just having long press reload. Also, there is a bypass proxy flag. Should we support that too?

**Comment by MortimerGoro** [comment]
@bluemarvin I'd keep the developer switch, it can help with discoverability and if you have to test a page tons of times it's quicker to use normal click than reload.

**Comment by bluemarvin** [comment]
@MortimerGoro @keianhzo I think this is ready to land. I think we should go with out changing the color or tooltip for now. Opinions?

**Comment by bluemarvin** [comment]
> In Pico devices (I guess related to Android 8) I get also the click event after the logn click.

Is there an Android 8 way to handle this?

**Comment by bluemarvin** [comment]
@keianhzo Okay, I think it is fixed.

**Comment by Softvision-GeluHaiduc** [comment]
I’ve performed exploratory testing on this new feature using the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 4K headsets, logged all the issues found and also written test cases to cover the new functionality.

**Pull request merged**
