### PR TITLE
update to new Google search codes (fixes issue #885)

### PR DESCRIPTION
**Pull request by cvan**
fixes issue #885. r? @mkaply to confirm.

<hr>

### context
- https://github.com/MozillaReality/FirefoxReality/issues/885
- https://github.com/mozilla-mobile/android-components/issues/1563
- https://github.com/mozilla-mobile/focus-android/issues/3917
- https://github.com/sblatz/android-components/commit/f3e5cb4
- https://dxr.mozilla.org/mozilla-central/source/browser/components/search/test/browser/browser_google.js
- https://dxr.mozilla.org/mozilla-central/search?q=google.com%2Fsearch&redirect=true

### CODE REVIEW

**Comment by mkaply** [comment]
Can you show me where this code is used? Does Reality report anything search related to telemetry?

**Comment by mkaply** [comment]
We need to get this fixed ASAP if we are getting more distribution.

**Comment by avrignaud** [comment]
+lars
- sent from my mobile

________________________________

**Comment by cvan** [comment]
> Can you show me where this code is used? Does Reality report anything search related to telemetry?

Yes, our Telemetry pings suggest that we are using a variety of search engines. (MoCo-Private Telemetry Query Dashboard: https://sql.telemetry.mozilla.org/queries/58566#151919)

> We need to get this fixed ASAP if we are getting more distribution.

@mkaply: per your review comment https://github.com/MozillaReality/FirefoxReality/pull/916#pullrequestreview-189217112, I made those adjustments to this PR. does it look good now?

P.S. I'm not familiar with the search system we have in place, but I'll help make sure we can ship out a new version ASAP. I'm not sure of the context, but @larsbergstrom can probably coordinate the logistics to make sure the malformed search queries can still been accounted for.

**Comment by larsbergstrom** [comment]
@MortimerGoro Can you please take a look at this code? It looks good to me.

@cvan @mkaply Unfortunately, we don't have any insights beyond our telemetry dashboard that tracks the queries performed to be able to see on the "backend" whether our search queries are working correctly or not, since it's aggregated with all Fx products sharing those codes.

**Comment by mkaply** [comment]
> @cvan @mkaply Unfortunately, we don't have any insights beyond our telemetry dashboard that tracks the queries performed to be able to see on the "backend" whether our search queries are working correctly or not, since it's aggregated with all Fx products sharing those codes.

That's actually what we need. Can we get access to your search telemetry data so we can integrate into the new dashboards once these codes are live?

**Comment by MortimerGoro** [comment]
@larsbergstrom LGTM

**Comment by larsbergstrom** [comment]
> That's actually what we need. Can we get access to your search telemetry data so we can integrate into the new dashboards once these codes are live?

If you check out the link @cvan provided to the internal query, in *theory* our data will just show up in any dashboard you write against Firefox search telemetry, as we are using the same reporting, but with `app_name in ('FirefoxReality_wavevr', 'FirefoxReality_oculusvr', 'FirefoxReality_googlevr')`.

Feel free to hit us up on Slack if you have more detailed questions on that bit!

**Comment by cvan** [comment]
@MozillaReality/fxr-eng @larsbergstrom @philip-lamb: now that this PR is merged to `master`, shall we cut a `v1.1.2` release for this?

**Comment by larsbergstrom** [comment]
@cvan Yes, we'll probably want both this fix and the one for bookmarks, which was blocking an update to Firefox Reality in the HTC store (they caught it during review!).

**Pull request merged**
