### PR TITLE
update Issue Template for better formating of error logs

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by bluemarvin** [comment]
This doesn't seem to work either, details seems to just strip out formatting. I had to just remove the details to get formatting to work.

<details open>
 
 ```
08-13 09:53:37.337 16359 16359 I VRB     : AudioEngine sounds preloaded!
08-13 09:53:37.347 16359 16751 I VRB     : Resize Swap Chain 2366,1547
08-13 09:53:37.352 16359 16751 I VRB     : 6DoF head tracking supported: False
08-13 09:53:37.352 16359 16751 I VRB     : Resume GVR tracking
08-13 09:53:37.362 16359 16751 I VRB     : Resume GVR controller
08-13 09:53:37.362 16359 16751 I VRB     : BrowserWorld::InitializeJava
08-13 09:53:37.367 16359 16751 I VRB     : BrowserWorld::InitializeGL
08-13 09:53:37.367 16359 16751 E VRB     : In onSurfaceChanged
08-13 09:53:37.368 16359 16751 I VRB     : Cached data: 1 size: 1024
08-13 09:53:37.368 16359 16751 I VRB     : SurfaceTextureFactory::InitializeGL
08-13 09:53:37.372 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 1
08-13 09:53:37.372 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 2
08-13 09:53:37.372 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 3
08-13 09:53:37.373 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 4
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 5
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 6
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 7
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 8
08-13 09:53:37.375 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 9
08-13 09:53:37.375 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 10
08-13 09:53:37.375 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 11
08-13 09:53:37.376 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 12
08-13 09:53:37.378 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 13
08-13 09:53:37.378 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 14
08-13 09:53:37.379 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 15
08-13 09:53:37.379 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 16
08-13 09:53:37.380 16359 16751 I VRB     : Allocate: 288 for GL_ARRAY_BUFFER: 17
08-13 09:53:37.380 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 18
08-13 09:53:37.380 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-5
08-13 09:53:37.381 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-3
08-13 09:53:37.381 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-2
08-13 09:53:37.381 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-1
 ```
 </details>

**Comment by cvan** [comment]
@bluemarvin: there's a GitHub-Markdown trick, which I've introduced in this PR, where you wrap your Markdown with a newline before and after, and everything renders correctly.

if you look closely, you'll see there is a blank newline both before and after the opening and closing `details` tag:

<details open>


```
08-13 09:53:37.337 16359 16359 I VRB     : AudioEngine sounds preloaded!
08-13 09:53:37.347 16359 16751 I VRB     : Resize Swap Chain 2366,1547
08-13 09:53:37.352 16359 16751 I VRB     : 6DoF head tracking supported: False
08-13 09:53:37.352 16359 16751 I VRB     : Resume GVR tracking
08-13 09:53:37.362 16359 16751 I VRB     : Resume GVR controller
08-13 09:53:37.362 16359 16751 I VRB     : BrowserWorld::InitializeJava
08-13 09:53:37.367 16359 16751 I VRB     : BrowserWorld::InitializeGL
08-13 09:53:37.367 16359 16751 E VRB     : In onSurfaceChanged
08-13 09:53:37.368 16359 16751 I VRB     : Cached data: 1 size: 1024
08-13 09:53:37.368 16359 16751 I VRB     : SurfaceTextureFactory::InitializeGL
08-13 09:53:37.372 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 1
08-13 09:53:37.372 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 2
08-13 09:53:37.372 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 3
08-13 09:53:37.373 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 4
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 5
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 6
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 7
08-13 09:53:37.374 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 8
08-13 09:53:37.375 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 9
08-13 09:53:37.375 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 10
08-13 09:53:37.375 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 11
08-13 09:53:37.376 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 12
08-13 09:53:37.378 16359 16751 I VRB     : Allocate: 384 for GL_ARRAY_BUFFER: 13
08-13 09:53:37.378 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 14
08-13 09:53:37.379 16359 16751 I VRB     : Allocate: 72 for GL_ARRAY_BUFFER: 15
08-13 09:53:37.379 16359 16751 I VRB     : Allocate: 6 for GL_ELEMENT_ARRAY_BUFFER: 16
08-13 09:53:37.380 16359 16751 I VRB     : Allocate: 288 for GL_ARRAY_BUFFER: 17
08-13 09:53:37.380 16359 16751 I VRB     : Allocate: 24 for GL_ELEMENT_ARRAY_BUFFER: 18
08-13 09:53:37.380 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-5
08-13 09:53:37.381 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-3
08-13 09:53:37.381 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-2
08-13 09:53:37.381 16359 16751 I VRB     : SetSurfaceTexture: crow::Widget-1
```

</details>

**Comment by cvan** [comment]
Perhaps I could literally add a `<!-- DO NOT REMOVE THIS LINE ABOVE -->` comment. suggestions? if it's that easy to mangle, I'm sure it'll happen in the future.

**Comment by bluemarvin** [comment]
Definitely a that comment, because I totally didn't understand 😅

**Comment by cvan** [comment]
@bluemarvin good to go now

**Pull request merged**
