### PR TITLE
Force tracking protection for Private Sessions

### LINKED ISSUE #3062: [Private Browsing] Tracking Protection can't be disabled from the shield icon button
**[Affected Versions]:**
- Firefox Reality version 10-140862313 (3db73db).

**[Affected Platforms]:**
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Click the Private browsing button from the tray.
2. Navigate to a website.
3. Click the shield icon from the Awesomebar
4. Click the "Disable" button from the pop-up and observe the behavior.

**[Expected results]:**
- The Tracking Protection is disabled and the shield icon is strikethrough.

**[Actual results]:**
- The Tracking Protection is not disabled and the shield icon is only briefly strikethrough.

**[Additional Notes]:**
- The websites are NOT added in the Exceptions list.
- This issue is not reproducible in normal browsing.
- I compared this behavior with the ones on Fenix and Desktop, where the Tracking Protection can't be disabled from the shield icon in PB.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=1sQtrD5xEkOv0M3nYUu0eSnrOkzSBRgp-).

### LINKED ISSUE #3064: [Private Browsing] The Tracking Protection shield icon is wrongly available for the PB description page
**[Affected Versions]:**
- Firefox Reality version 10-140862313 (3db73db).

**[Affected Platforms]:**
- HTC Vive Plus - Android 7.1.2
- Pico Neo 2 - Android - 8.1.0
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**                                        
1. Click the Private Browsing button from the tray.
2. Observe if the Tracking Protection shied icon is displayed.

**[Expected results]:**
- The icon is not displayed.

**[Actual results]:**
- The icon is displayed.

**[Additional Notes]:**
- Attached is a screen shot of the issue:
org mozilla vrbrowser-20200327-152459

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #3064 Fixes #3062 Hide ETP button in PB and force tracking protection for Private Sessions based on https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?as=u&utm_source=inproduct:
> Tracking content in Private Windows only. These trackers are hidden in ads, videos, and other in-page content. Blocking them can cause some websites to break. To add this protection in all windows, visit your privacy preferences and select Strict or Custom as explained below.

### CODE REVIEW

**Comment by keianhzo** [comment]
I've fixed the visibility issues. Regarding ETP not working in Private Browsing I've opened a GV issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1627185

**Comment by bluemarvin** [comment]
@keianhzo I think this is good except for the GV bug. Should we just land this and then follow up the GV bug when it gets fixed there? Not sure when that will be.

**Comment by bluemarvin** [comment]
We need to be reloading the Session instead of recreating it, but are currently blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1625585

**Comment by bluemarvin** [comment]
Fixes #3132

**Pull request merged**
