### PR TITLE
Set WebVR sitStanding transform. Set WebVR neck model for 3DOF devices.

### LINKED ISSUE #770: Sketchfab controller issues
## Hardware
Oculus Go

## Steps to Reproduce
1. Go to sketchfab.com
2. Open any low poly model
3. Enter inmersive mode

## Current Behavior
The pointer inside Sketchfab seems to be shifted and seems to come out from the head instead of the hand.

Also the trigger button doesn't work.

ezgif com-video-to-gif

## Expected Behavior
The controller should be located at the hand position.

ezgif com-video-to-gif 1

## Error Logs and Stack Traces
<details open>

```
```

</details>

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #770

We need to wait for this Gecko patch
https://bugzilla.mozilla.org/show_bug.cgi?id=1537899

### CODE REVIEW

**Comment by bluemarvin** [comment]
@MortimerGoro Does this need to be done for Daydream as well since clip-in are only 3DoF?

**Comment by bluemarvin** [comment]
Also, there are 3DoF Wave devices like the Pico G2

**Comment by MortimerGoro** [comment]
@bluemarvin Updated the PR adding setting the sitStanding matrix to Wave and Daydream. Sketchfab demo & position controllers looks good on Vive 6DOF (I don't have a Wave 3dof device to test in)

I'm merging this to tag the release for today. Create a follow-up issue if you find anything.

**Comment by bluemarvin** [comment]
> @bluemarvin Updated the PR setting the sitStanding matrix in Wave and Daydream. Sketchfab demo & position controllers looks good in Vive 6DOF (I don't have a Wave 3dof device to test in)

@cvan, can you test with the Pico G2 to make sure sitStanding matrix is as expected?

**Pull request merged**
