### PR TITLE
Enable hardware renderer and don't draw after onStop/onDestroy

### LINKED ISSUE #2428: [Oculus] Movement is choppy and there are glitches in the Bookmark/History Views if the window size is greater than 0.5x
**[Affected Versions]:**
-  Firefox Reality version 7 RC6 (b01367aa)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1

**[Prerequisites]:**
- The Firefox Reality browser is opened.

**[Steps to reproduce]:**
1. Resize the window to 3x size.
2. Click the Bookmark/History button in the menu tray.
3. Move the headset vertically or horizontally and observe the behavior.

**[Expected results]:**
- The movement is smooth and there are no visual glitches.

**[Actual results]:**
- The movement is choppy and there are visual glitches.

**[Notes]:**
- The issue is reproducible with any window size greater than 0.5x size.
- The issue is most visible if the window is 3x size.
- The glitches are not visible in the video recording.
- The issue is not reproducible on the HTC devices.
- Attached a screen recording of the issue [here](https://drive.google.com/open?id=18s7nPoxXWOIxzbk0NhBqOn_c2pM6B7o9).
- Attached the logcat file of the issue [here](https://drive.google.com/open?id=1eQ40s8jJ5rc2WJ8InXLevBfMIGYTEN7S).

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #2428

### CODE REVIEW

**Comment by MortimerGoro** [comment]
@Softvision-GeluHaiduc can you try to reproduce #1959 in this feature branch? We have switched back to hardware rendering to fix the choppiness issues in #2428, but now we also stop rendering when closing the app, which we believe can fix the original issue in #1959

**Comment by bluemarvin** [comment]
APKs are available here: https://community-tc.services.mozilla.com/tasks/GjfwbxrARvaIjQd540twPw#artifacts

**Comment by Softvision-GeluHaiduc** [comment]
@MortimerGoro I’ve tried to reproduce #1959 using the apk from above on the Oculus Quest device and managed to reproduce the issue. 
Then I tried to reproduce the issue using the debug build and with the logcat started, I managed to crash the app 2 more times entering immersive mode, both 360 videos and other immersive experiences, and quitting the app. The logcat can be found [here](https://drive.google.com/open?id=1aj8GmySBNu8I90O1CGDZrATqHX6PWZyv). 
Regarding issue #2428 the issue is no longer reproducible on this build.

**Comment by MortimerGoro** [comment]
I have checked the exitings crashlog and it's not caused by the original issue
https://crash-stats.mozilla.com/report/index/8569079a-5392-4769-ac96-632320191217

@bluemarvin are you aware of this bug? the crash happens in GV Autofill
```
java.lang.NullPointerException
	at org.mozilla.geckoview.Autofill$Support.clear(Autofill.java:1138)
	at org.mozilla.geckoview.Autofill$Support$1.handleMessage(Autofill.java:975)
	at org.mozilla.gecko.EventDispatcher$3.run(EventDispatcher.java:373)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6144)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by MortimerGoro** [comment]
@Softvision-GeluHaiduc This is ready to test again, artifacts are here: https://community-tc.services.mozilla.com/tasks/A7ViQii_R4yrIdH0NHoBVw#artifacts

**Comment by Softvision-GeluHaiduc** [comment]
@MortimerGoro I tried to reproduce the issue using the above build but it seems that the issue is no longer reproducible, I tried it both on the Oculus Quest and Go.

**Pull request merged**
