### PR TITLE
Implements latest Settings spec

### LINKED ISSUE #1372: Settings IA and verbiage updates
See https://trello.com/c/P52DGGmp/88-uis-16-settings for all changes. 

This ticket covers these items:
- Reorganizing the Privacy and Security category (200) and updating text (300b)
- Reorganizing Language settings (200 and 300a)
- Moving "Autoplay Media" to the Display category (300c)
- Removing user agent control from Display category (and adding it to the awesomebar instead - needs #962 )
- Adding Help category to Settings and removing it from the Tray. Functionality is the same, just in a new location.

fixes #1242, fixes #994 and fixes #752

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #1372 #962 #1440 This PR implements the latests Settings spec which also includes the new user agent switch button in the navigation bar.

### CODE REVIEW

**Comment by philip-lamb** [comment]
Awesome. Will give it a test tomorrow.

**Comment by MortimerGoro** [comment]
cc @jvonitter @thenadj related to the checkmark idea I mentioned:

Firefox desktop uses this icon to enable `Mobile/Responsive layout`. It changes color when enabled/disabled.
Captura de pantalla 2019-07-19 a las 11 53 18

Firefox for iOS uses this icon to go back to `Mobile/Responsive layout` once desktop is enabled. It's the same idea of using a checkmark.
Captura de pantalla 2019-07-19 a las 11 58 51

**Comment by bluemarvin** [comment]
I'm not sure if it is related but the first time I ran this PR only the main window was visible, no other UI was visible. I had to restart to see the rest of the UI like navigation bar and tray.

**Comment by bluemarvin** [comment]
Also, I really do not like the `VR` in the navigation bar. It looks very heavy and it's purpose is not immediately obvious.

**Comment by jvonitter** [comment]
new icons!
[UA_Icons.zip](https://github.com/MozillaReality/FirefoxReality/files/3424136/UA_Icons.zip)

**Pull request merged**
