### PR TITLE
Update grade & build tools

### PR DESCRIPTION
**Pull request by MortimerGoro**

### CODE REVIEW

**Comment by bluemarvin** [comment]
This needs to wait until I get the docker image updated. Currently blocked on a slow curl upload to autograph.

**Comment by daoshengmu** [comment]
The failure is because `robolectric` needs to use SDK 28, otherwise, you can choose to upgrade it to `4.3.1`. However, it needs Java 9.

**Comment by keianhzo** [comment]
@daoshengmu It seems that we can force Robolectric to use SDK 28. I've pushed a fix.

**Comment by daoshengmu** [comment]
> @daoshengmu It seems that we can force Robolectric to use SDK 28. I've pushed a fix.

It works properly for me. GJ!

**Pull request merged**
