### PR TITLE
Correctly handle surface resize after the surface is taken by another layer.

### LINKED ISSUE #1630: The old 3x size window is positioned away from the newly created window
**[Affected Versions]:**
- Firefox Reality 1.4-32332324 (22.08.2019) 

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Resize the window to 3x size.
2. Click the new window button "+" from the tray.
3. Observe the old window from position 1.

**[Expected results]:**
- The old window is resized to 2x size and positioned next to the new window.

**[Actual results]:**
- The old window is resized to 2x size but it is positioned away from the new window.

**[Notes]:**
- The issue is not reproducible on the Oculus Quest because it is blocked by #1619.
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1CsW_EpC77u3npW4RuSY5nW4yWSQy0o3S/view?usp=sharing)

### LINKED ISSUE #1634: The remaining window is not rendered correctly after another window was closed
**[Affected Versions]:**
- Firefox Reality 1.4-32332324 (22.08.2019)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Resize the window to 3x size.
2. Click the new window button "+" from the tray.
3. Close the active window.
4. See if the remaining window is rendered correctly.

**[Expected results]:**
- The remaining window is rendered correctly.

**[Actual results]:**
- The remaining window is not rendered correctly and is of a different size.

**[Notes]:**
- Attached a screen recording of the issue: [link](https://drive.google.com/file/d/1XoMRV-06HDz4nUOgyqxs-wUHbwGoYfJE/view?usp=sharing)

### LINKED ISSUE #1637: The app crashes after multiple windows are resized to the max size
**[Affected Versions]:**
- Firefox Reality 1.4-32332324 (22.08.2019)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Resize the window to 3x size.
2. Click the new window button "+" from the tray.
3. Resize the window to 2x size.
4. Click the new window button "+" from the tray.
5. Observe what happens.

**[Expected results]:**
- A new window is created.

**[Actual results]:**
- The app crashes.

**[Notes]:**
- Attached a screen recording of the issue [here](https://drive.google.com/file/d/1Q2FdheABxyCBGvWAiuHgpzDU7q5aP-Z7/view?usp=sharing).
- Attached the logcat file [here](https://drive.google.com/file/d/1Q-LLgYjIB5mCXU4vmpsFXHz2ytxA9CC_/view?usp=sharing).

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #1630. Fixes #1634. Fixes #1637.

### CODE REVIEW

**Comment by bluemarvin** [comment]
Weird, it says taskcluster failed but when you follow the details link, it shows it passing.

**Comment by MortimerGoro** [comment]
@bluemarvin I clicked rerun task in Taskcluster. The first error was a intermittent, a maven connection failure

**Comment by bluemarvin** [comment]
Ah, I wish it would update on github when it gets rerun.

**Comment by MortimerGoro** [comment]
@keianhzo I'm merging this so it starts getting tested by QA. Add a follow-up if you find something

**Pull request merged**
