### PR TITLE
Update to A-C 39.0.1

### PR DESCRIPTION
**Pull request by grigoryk**
This appears to work well, I'm still testing it out (but, only in an emulator since I don't have a VR device handy). 

cc @pocmo

### CODE REVIEW

**Comment by pocmo** [comment]
Thank you, Grisha! I'll give it a try on my Quest too. :)

**Comment by pocmo** [comment]
Did some tests and I was able to login, sync and send tabs to other devices. However if I sent tabs to the device itself then they never showed up. But I am not sure whether that is caused by the version bump.

**Comment by pocmo** [comment]
I switched back and forth between `master` and a branch with your patch applied. Only on `master` I was able to get a tab sent from my desktop to show up after manually synchronizing. The tabs I've sent previously (with the patched version) do not suddenly show up though - so I wonder if they have been received but dropped on the floor?

**Comment by pocmo** [comment]
Looking at the log we receive one device event for the synced tab. But the problem seems to be around here:

```
val filteredEvents = events.filterIsInstance(DeviceCommandIncoming.TabReceived::class.java)
```

This instance check is never true. We receive an `AccountEvent.DeviceCommandIncoming`. But this is not the same as the `DeviceCommandIncoming` class `TabReceived` is defined on. 🤔 

https://github.com/mozilla-mobile/android-components/blob/b1f8371fcdf7a4b1501c31b7753ca263088caea2/components/concept/sync/src/main/java/mozilla/components/concept/sync/AccountEvent.kt#L38

vs.

https://github.com/mozilla-mobile/android-components/blob/b1f8371fcdf7a4b1501c31b7753ca263088caea2/components/concept/sync/src/main/java/mozilla/components/concept/sync/AccountEvent.kt#L22

**Comment by pocmo** [comment]
It is fixed after unpacking the event first:

```Kotlin
val filteredEvents = events
    .filterIsInstance(AccountEvent.DeviceCommandIncoming::class.java)
    .map { it.command }
    .filterIsInstance(DeviceCommandIncoming.TabReceived::class.java)
```

**Comment by keianhzo** [comment]
There is a Draft PR with the Glean and AC updates waiting to be landed when we are done with the current release: https://github.com/MozillaReality/FirefoxReality/pull/3096

I might compare and update that one with whatever we have missed from this one.

**Comment by grigoryk** [comment]
Ah, thanks for the catch @pocmo !

@keianhzo PR in #3096 looks good to me - well, it should go to a higher A-C version now.

**Comment by keianhzo** [comment]
Thanks for the review @grigoryk. I've updated AC in the other PR, I guess we can close this one.

**Comment by grigoryk** [comment]
Yup!

**Pull request closed without merging**
