### PR TITLE
Avoid logging youtube redirects due to url override

### LINKED ISSUE #1839: Two or three history feeds are wrongly logged when URL is change via javascript
**[Affected Versions]:**
- Firefox Reality 1.5-32570012 (6090cf4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Click the "+" button to open a new window (I opened a new window for a better observation of the issue).
2. Click the "History" button to open the "History" page.
3. Focus the other window and navigate to "www.youtube.com".
4. Click on a suggested video and observe the "History" page.

**[Expected results]:**
- A history feed is logged for the opened video.

**[Actual results]:**
- Two or three history feeds are logged for the opened video.

**[Notes]:**
- The logs have the same URL.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=19oP4kQI-bfkgv0nQlmM1LfUzD7fWxXUd)

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #1839 Avoid storing a youtube history entry when is the result of a youtube url override

### CODE REVIEW

**Comment by bluemarvin** [comment]
I'm seeing the same URL four times from youtube:
org mozilla vrbrowser-20190924-171723

**Comment by keianhzo** [comment]
@bluemarvin updated

**Comment by bluemarvin** [comment]
I think we  want to use this: https://bugzilla.mozilla.org/show_bug.cgi?id=1555337 but it isn't scheduled to be worked on until October at the earliest. I'm not sure it is worth adding this work around as it only works for YouTube. Other sites that set `window.location` will still have multiple entries such as twitch.tv.

**Comment by bluemarvin** [comment]
@jvonitter and @MortimerGoro, do either of you have an opinion on this?

**Comment by jvonitter** [comment]
I'm ok waiting until we can do it properly. October is pretty soon.

**Comment by bluemarvin** [comment]
Still blocked by GeckoView. moving to v7.

**Comment by keianhzo** [comment]
Closed as we are doing this using the new `hasUserGesture` LoadRequest param.  https://github.com/MozillaReality/FirefoxReality/pull/2417

**Pull request closed without merging**
