### PR TITLE
Fix cropped awesome bar placeholder

### LINKED ISSUE #1718: The placeholder from the Awesomebar is not entirely visible  when the window is resized to the "0.5x" size
**[Affected Versions]:**
- Firefox Reality 1.4-32420004 (RC1) build.

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- Oculus Quest - Android 7.1.1
- HTC Vive Focus Plus - Android 7.1.2

**[Prerequisites]:**
- Have the latest Firefox Reality 1.4-32420004 (RC1) build installed.
- The headset is turned on and the app is opened.

**[Steps to reproduce]:**
1. Click the "Resize" button from the right size of the Awesomebar.
2. Select the "0.5x" size.
3. Click the check mark so that the resize is applied.
4. Observe the Awesomebar's placeholder.

**[Expected results]:**
- The "Search the web or enter address" placeholder is displayed.

**[Actual results]:**
- The "Search the web or" placeholder is displayed.

**[Notes]:**
- For the Oculus Go device, half of the first letter from the "enter" string is also displayed.
- Attached are a screen shots of the issue:
Capture

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #1718

### CODE REVIEW

**Comment by bluemarvin** [comment]
@jvonitter What's the intention here? Should the entire placeholder be visible? This PR prevents the placeholder from getting cropped prematurely but the place holder doesn't fit into the url bar.
org mozilla vrbrowser-20191003-093457

**Comment by jvonitter** [comment]
This is the intended design.
I don't think we need to squish the buttons together, but we should use the gradient at the end to show the text is being cut off.
[BUG-28_Url_bar_for_small_window_size_001.pdf](https://github.com/MozillaReality/FirefoxReality/files/3687241/BUG-28_Url_bar_for_small_window_size_001.pdf)

**Comment by keianhzo** [comment]
@jvonitter @MortimerGoro Android doesn't support fading edge for the hint. We can add enable elipsis support to that the text is not cut, that works for the hint and the text still gets the fading edge.

**Comment by MortimerGoro** [comment]
@bluemarvin @keianhzo Ready for re-review. I used a custom view with gradient as a workaround for the unsupported hint fading support in Android.

**Pull request merged**
