### PR TITLE
Fix loading icon stuck on startup

### LINKED ISSUE #855: Loading icon stuck on startup
Sometimes the loading icon in the URL bar shows a big circle at startup, with no animation.

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #855

### CODE REVIEW

**Comment by MortimerGoro** [comment]
I was able to reproduce the problems in this branch using the youtube as the default URL.

After more research found that the problem is caused on Android pause/resume events. We need to pause and resume the animation view on those situations

**Comment by cvan** [comment]
@MortimerGoro let me know when you're ready for a re-review. thank you for taking a deep dive here 👍

**Comment by MortimerGoro** [comment]
@cvan it's ready for re-review

**Comment by MortimerGoro** [comment]
I'm going to merge this one. Create some follow-up if you find something else

**Pull request merged**
