### PR TITLE
Bumps telemetry expiration dates to 2021-05-01

### PR DESCRIPTION
**Pull request by keianhzo**
Bumps telemetry expiration dates to 2021-05-01

### CODE REVIEW

**Comment by keianhzo** [comment]
# Request for Data Collection Renewal

** This form is for the renewal of an existing, reviewed data collection.**

** All questions are mandatory.
You must receive Data Review from a
[Data Steward](https://wiki.mozilla.org/Firefox/Data_Collection)
on a filled-out Request before shipping your renewed data collection.**

1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/MozillaReality/FirefoxReality/pull/2241#issuecomment-555285627
https://github.com/MozillaReality/FirefoxReality/pull/2327#issuecomment-558139174
https://github.com/MozillaReality/FirefoxReality/pull/2348#issuecomment-558835389

2) When will this collection now expire?
2021-05-01

3) Why was the initial period of collection insufficient?
It is because we would like to check if they are still useful every 6 months.

**Comment by keianhzo** [comment]
> # Request for Data Collection Renewal
Per https://github.com/MozillaReality/FirefoxReality/pull/3896#issuecomment-714389391

@harraton Please help data review.

The metrics document is here, https://github.com/MozillaReality/FirefoxReality/blob/bumpGleanDates/docs/metrics.md, and it will be shown in docs/metrics.md once we merge it.

The wiki page is here, https://github.com/MozillaReality/FirefoxReality/wiki/Telemetry#new-telemetry-system---glean

**Comment by keianhzo** [comment]
@Dexterp37 Please help review as well.

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 Please help review as well.

Note that this does not require a Glean / telemetry peer. You only need data-reviews and a review from your own team :)

**Comment by daoshengmu** [comment]
The PR looks good to me. We generally put the data reviewer reply link into the block of *data_reviews:* instead of using the PR link. You can consider to update it once you have a data-review+

**Comment by keianhzo** [comment]
@Dexterp37 do you know if we are pinging the right steward for the data review here? Any other person we should ping?

**Comment by Dexterp37** [comment]
> 
> 
> @Dexterp37 do you know if we are pinging the right steward for the data review here? Any other person we should ping?

Hey @keianhzo , the data-review process is [documented here](https://wiki.mozilla.org/Firefox/Data_Collection). It also includes a list of people and a channel where to ask for help ;-)

**Comment by keianhzo** [comment]
Thanks @Dexterp37! 

@chutten Could you please help review the request?

**Comment by chutten** [comment]
Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes.

    Is the data collection covered by the existing Firefox Privacy Notice?

Yes.

---
Result: datareview+

**Pull request merged**
