### PR TITLE
Support loading an environment from a known location. Fixes #207

### LINKED ISSUE #207: Support loading an environment from a known location
Suggestion: in order to make it easier for the art team to iterate on-device more quickly, it would be nice if we could probe a known location (e.g. `/sdcard/reality/FILE`) before loading the version of the environment in the app package. Then, they could iterate locally, `adb push` their changes, and restart the app to see it rather than having to drop it to the engineering team.

cc @MortimerGoro @keianhzo @thenadj

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #207

Depends on https://github.com/MozillaReality/vrb/pull/39/files

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Example of injected environment in the data file of the app (via adb or Android File Transfer):

captura de pantalla 2018-07-20 a las 16 40 54

**Comment by bluemarvin** [comment]
Issue #231 must be resolved before we ship.

**Comment by MortimerGoro** [comment]
yes, it needs to be disabled for release. Some options:

- Enable only on debug builds
- Include a FxR dev mode (e.g. clicking on the logo in about) to show a menu with some toggle options.
- Manually disable it before ship

**Comment by keianhzo** [comment]
I think enabling it only in debug builds is the most straightforward way without new UI and involving design.

**Comment by bluemarvin** [comment]
Enabling on debug is probably okay. But I also want to insure we fix the ModelLoaderAndroid API and classes so that it is explicit where the model is being loaded from in code. I don't want to use the path as the switch for where the model gets loaded from.

**Comment by larsbergstrom** [comment]
The goal here is to enable the designers - including those not on our team - to grab a build from the store and use it to iterate on environments while we work on building out more complete in-browser configuration UI.

I'm fine with a config flag as long as it's easy to turn on.

Sideloading custom builds is unfortunately proving to be extremely error-prone for non-developers, so I'd prefer to avoid grabbing builds from TC or a developer and asking designers to sideload them.

Is the concern here security or users getting attached to using it as a configuration point we have to then support forever? I'm not super concerned about the security issues, given that it's coming from local storage, but happy to do a formal review.

**Comment by bluemarvin** [comment]
I'm not thrilled about shipping a backdoor that users don't explicitly turn on.

**Comment by bluemarvin** [comment]
But there is also the code API, from reading the code right now there is no way to tell where the model is loaded from with out going into the guts of the implementation and then also know the path of what is being loaded. I would prefer it to be more explicit.

**Pull request merged**
