### PR TITLE
Only allow prefs to be set by extras in debug builds

### PR DESCRIPTION
**Pull request by bluemarvin**

### CODE REVIEW

**Comment by bluemarvin** [comment]
Fixes #3348

**Comment by fernandojsg** [comment]
I agree on the point of disabling all the prefs by default letting the user to set them if they want, but why can you also set them when running the app through an adb command, it could be useful to have access to that or at least having just a pref that you could accept other prefs by command line?

**Comment by bluemarvin** [comment]
> I agree on the point of disabling all the prefs by default letting the user to set them if they want, but why can you also set them when running the app through an adb command, it could be useful to have access to that or at least having just a pref that you could accept other prefs by command line?

We need a quick fix for v10. I filed this as follow up https://github.com/MozillaReality/FirefoxReality/issues/3354

**Comment by fernandojsg** [comment]
OK, it makes sense, thanks!

**Pull request merged**
