### PR TITLE
Fixes #1857 Added option to disable domain autocomplete in the address bar

### LINKED ISSUE #1857: Settings for turning off and clearing autocomplete
Users need a way to turn off autocomplete in the address bar.
They also need a way to clear past autocomplete information.

### PR DESCRIPTION
**Pull request by keianhzo**
Fixes #1857 Added a privacy setting to enable/disable the history/bookmarks based autocomplete in the awesome bar.

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Fixes #2558

**Comment by bluemarvin** [comment]
I've made some comments in the issue. I'm not sure we have the correct spec for this feature.

**Comment by keianhzo** [comment]
@bluemarvin @MortimerGoro I guess we should close this one?

**Comment by bluemarvin** [comment]
> @bluemarvin @MortimerGoro I guess we should close this one?

I think we want the functionality, but we need to resolve how the auto suggestion code should work.

**Comment by emstanley** [comment]
We added a toggle to the design, but we didn't add it to this issue. See screenshot and design notes below.

image

 https://trello.com/c/P52DGGmp/88-uis-16-settings

**Comment by keianhzo** [comment]
@emstanley I think we talked about movingthis one to v11? I think the functionality is not clear at this point, we probably will need to go over this one to redefine it.

**Comment by keianhzo** [comment]
Closing in favor of https://github.com/MozillaReality/FirefoxReality/pull/3551

**Pull request closed without merging**
