### PR TITLE
Hand Tracking in Firefox Reality

### PR DESCRIPTION
**Pull request by SheepGit**
Hey, I'm new to Github so I may have put this request in completely the wrong spot. If so, I apologize in advance. I was wondering as to the progress of hand tracking in Firefox Reality. Is there currently any way to implement such a feature? I understand this may still be in development atm, and I'm willing to help with its release by becoming a tester if you all believe it will help boost progress on this project.

I'd really like to see this feature come to the Quest 2, so please let me know as to the progress of this feature and whether or not I may be of use as a tester of the aforementioned software.

Thank you for taking the time to read my request and have a lovely day!

### CODE REVIEW

**Comment by enovikov11** [comment]
you have commented code, thats bad practice, please remove it

as i know firefox already have hand tracking, please describe problem you are going to solve

**Comment by enovikov11** [comment]
voting for closing PR

**Comment by SheepGit** [comment]
I'm not exactly sure what this is about, but you can remove whatever
comment I made. No problem. Sorry for making that comment there.

**Comment by jaredhirsch** [comment]
@SheepGit Hey, since you're new to github: I think normally a feature request would be filed as a bug, not as a pull request. IMO the best approach would be to close this pull request and just file an issue asking about progress.

Also, from the issue view, you can search for existing bugs. It looks like there are a few asking about hand tracking already, though most are rather old: https://github.com/MozillaReality/FirefoxReality/issues?q=is%3Aissue+is%3Aopen+hand+tracking

**Pull request closed without merging**
