### PR TITLE
180/360/3D video support

### PR DESCRIPTION
**Pull request by MortimerGoro**

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Depends on https://phabricator.services.mozilla.com/D9026

**Comment by cvan** [comment]
as `360` is probably most common, can we have that be the first option, instead of `3D Side by Side`?

**Comment by cvan** [comment]
I had some compilation errors when I tried to rebase it locally against `master`. if you can rebase and update, that'd be awesome :smile: thanks!

**Comment by thenadj** [comment]
Fine to change order to show 360 as first option. UIS won't be updated for that. Please make adjustments accordingly.

**Pull request merged**
