### PR TITLE
Closes #3269 Adds Tooltips to the video controls

### LINKED ISSUE #3269: The on screen controls in immersive mode do not have tooltips
**[Affected Versions]:**
- Firefox Reality version 10 RC2 (17a313b4)

**[Affected Platforms]:**
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- Pico G2 4K - Android 8.1.0

**[Prerequisites]:**
- The Firefox Reality browser is open.

**[Steps to reproduce]:**
1. Navigate to a 360 video on YouTube and enter immersive mode.
2. Press the trigger button on the controller to have the on screen controls displayed.
3. Using the controller hover the pointer for more than ~1 second over each button.
4. Observe the tooltips.

**[Expected results]:**
- The tooltip for each button is displayed.

**[Actual results]:**
- The tooltip for the buttons are not displayed.

**[Notes]:**
- This [trello card](https://trello.com/c/DN6fXAmz/153-uis-40-tooltips) was used as reference.

### PR DESCRIPTION
**Pull request by keianhzo**
Closes #3269 Adds tooltips to the video controls. Also adds support for curved tooltips, it seems it was lost in some rebase.

### CODE REVIEW

**Comment by bluemarvin** [comment]
Video control tool tips should not be curved when there are multiple windows. Should be handled the same as the tray and have `setCurvedTooltip(false)` invoked.
One window:
image
Two windows:
image

The fullscreen video UI has the same problem:
image

**Comment by bluemarvin** [comment]
I wonder if it would be easier to make tool tips flat by default and only make them curved for the navbar?

**Comment by keianhzo** [comment]
@bluemarvin updated to be flat by default and only curve navigation bar tooltips. Also added a tooltipCurved property to set it in the layout XML.

**Comment by keianhzo** [comment]
@bluemarvin Updated. Now by default the parent's curved mode is used unless a `tooltipCurved` property is added to the tooltip layout, in that case that one is used.

**Pull request merged**
