### PR TITLE
Set youtube viewport before DOMContentLoaded

### LINKED ISSUE #2542: The Youtube website is horizontally scrollable after navigating back from another website
**[Affected Versions]:**
- Firefox Reality version 8-33580132 (83024a6).

**[Affected Platforms]:**
- Oculus Quest - Android 7.1.1
- Oculus Go - Android 7.1.2
- HTC Vive Focus Plus - Android 7.1.2
- HTC Vive Focus - Android 7.1.2

**[Prerequisites]:**
- The headset is turned on and the browser is opened.

**[Steps to reproduce]:**
1. Navigate to Youtube website
2. Navigate to another website.
3. Click the "Back" navigation button.
4. Observe the Youtube's layout.

**[Expected results]:**
- The website fits the windows view.

**[Actual results]:**
- The website is horizontally scrollable.

**[Notes]:**
- This issue is also reproducible after quitting and resuming the app.
- This issue is more damaging for small resized windows.
- Needed by #1760.
- Attached is a screen recording of the issue: [link](https://drive.google.com/open?id=11elYcEYMhGFwFb_Q3AHvQUcabJ8oKdan)

### PR DESCRIPTION
**Pull request by MortimerGoro**
Fixes #2542

### CODE REVIEW

**Comment by bluemarvin** [comment]
This fixes the back button issue but if I load a youtube video it looks like:
org mozilla vrbrowser-20200107-125730
If I quit FxR with that page loaded and then restart, it looks like this:
org mozilla vrbrowser-20200107-125708

**Comment by keianhzo** [comment]
This seems to have fixed the reload viewport (the page got zoomed if reloaded while in a video page) issues. For some reason I can't reproduce Randall's bove issue.

**Comment by bluemarvin** [comment]
> This seems to have fixed the reload viewport (the page got zoomed if reloaded while in a video page) issues. For some reason I can't reproduce Randall's bove issue.

To reproduce:

1) Go to youtube video
2) Exit FxR by pressing the oculus home button.
3) Kill FxR `adb shell am force-stop org.mozilla.vrbrowser`
4) Launch FxR

**Comment by MortimerGoro** [comment]
PR updated with the fix for the restore issue

**Comment by MortimerGoro** [comment]
WebExtension onBeforeSendHeaders is not run for the main frame when restoring a session, so we need to duplicate UA setter in both sides (WebExtension and GV API)

**Comment by MortimerGoro** [comment]
fixes #2557

**Pull request merged**
