### PR TITLE
Implement inverse touch function for UI automated testing in noapi

### PR DESCRIPTION
**Pull request by MortimerGoro**
This is a helper function for QA to start doing some automating UI testing in noapi

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Here is an example using the API: https://github.com/MozillaReality/FirefoxReality/tree/experimental/inverse_touch_test

It automatically clicks the private browsing button from the tray regardless of camera position

**Comment by jrbenny35** [comment]
Is there a way this could be used with a test runner?

**Comment by bluemarvin** [comment]
I'm hesitant to land code that doesn't get used as it tends to rot quickly. Does it make more sense to create a feature branch for testing and land this there?

**Comment by MortimerGoro** [comment]
@bluemarvin I updated the PR to land it in a feature branch. Also removed this from https://github.com/MozillaReality/FirefoxReality/milestone/14

**Pull request closed without merging**
